== 序言

在正式开始配置之前，还是要简单说一下我的思路的。

=== Why?

我希望接下来配置的这台机器能满足我在家的一切智能需求，从简单的文件共享，到智能家居的集中控制，再进一步包括神经网络的入门探索、源代码的编译测试。所以我需要一台全功能的服务器，包括NAS、智能家居中枢、源代码托管、编译服务器等功能。这需要这台机器达到如下的几项性能指标：

- 含有具有热插拔功能的多盘位
- 至少2.5G的网络功能
- 说得过去的多核性能，优先于单核性能
- 一张计算卡
- 不沉重的成本

在此基础上，可以追求在这台AIO服务器增加一些定制化的功能：

- 更好的效能
- 尽量静音
- 尽量好看（是的，我是颜狗）

=== What?

在基本要求确定下来后，根据需求的优先级开始写配置单。

- *机箱：半人马座β* 保证足够的扩展性的同时，又具备不错的质感与工业设计
- *主板：技嘉x99-ud4* 能充分利用x99工作站cpu含有的40条pcie通道，提供足够的扩展性，不存在瓶颈
- *CPU：E5-2696v4* 多核性能还可以的x99平台CPU，性价比较高
- *散热器：2U内下压散热器* 这个没什么要求，主要考虑的是噪音问题，150w的解热能力算是标配，考虑到主板和机箱的兼容性问题，选了15mm的薄扇+50mm的三层下压散热器，不知道能不能装上
- *内存：纯ECC内存 16*8=128GB* 查了下主板的dataSheet，这是这块主板支持的最大的UDIMM容量，RDIMM能突破1T，但是对内存的要求较高（1Rx8），不考虑
- *系统盘：致钛TiPlus5000 2T* 一块PCI-E3.0的NvmeSSD，支持下国产
- *缓存盘：致钛SC001 XT SATA 500G*2* 缓存盘的性能没有什么要求，主要是和机械硬盘比
- *数据盘：希捷银河16T ST16000NM000J* 比起小容量的NAS盘，不如直接上大容量的企业盘更有性价比，找了个靠谱的店买了两块拆机盘
- *电源：TT钢影 sfx 650w* 考虑到硬盘的满载功率甚至能碰到200w，加上必要的冗余，一个450w的电源就不是很可靠了。_（提一嘴，星之海他家有针对于这款电源的定制线，但是只支持450w的型号，问了客服说是功率的问题。我看了下模组线的规格，17AWG的线径正常来说别说是650w，1000w电源的定制线也够用了。不过为了保险起见，还是多花了10块钱选了另行定制。你最好是有给我用粗线缆）_ *_(2023.10.15更新：晚上看到模组线发货了，一问客服，果然是客服不了解的问题，随机箱一起发货了，看来是我想多了)_*
- *SATA扩展卡：PCI-E转SFF-8643*2扩展卡* 看了下主板的dataSheet，在使用m2固态的情况下，主板自带的6个SATA接口只能用4个，再加上缓存盘就不够用了，干脆就加一块扩展卡，正好两边都是8643
- *显卡：UEFI亮机卡* 本来想直接上个P4或者A2000的，但是还没弄清Unraid+x99的组合能不能提供足够的兼容性支持，所以先上个亮机卡凑合用着
- *电口网卡：Intel i225/i226 四口2.5G电口网卡* Intel的网卡要比Realtek的贵出不少，但是自组AIO最要紧的是稳定，还是相信大厂的实力吧
- *光口网卡：Intel x520 四口万兆光口网卡* 其实挺惊讶的，半高的卡竟然能拓展出四个万兆光口，现在有点慌，怕不是假四口
- *网络：2.5G交换机、六类网线* 根据网络环境配置满足基本要求的网线，交换机主要是用来减缓AIO压力的，专业的活还是交给专业的人来干吧
- *外设：红米1A显示器、原有Dell键盘、爱国者有线鼠标* 这块没啥好说的，突出一个能用就行
- *其他杂七杂八的东西：硅脂、风扇、U盘、插排……* 这块不会挑，尽量选品牌就行，性价比一般，但是品控不错

=== Then...

简单算下满配下的极限功率。

- CPU（满载）：120w
- 主板：35w
- 内存：10w
- 机械硬盘（启动功率）：104w
- 固态硬盘（写入功率）：100w
- 电源风扇：10w
- pcie设备（各设备满功率）：20w+20w+70w+10w
- 机箱风扇（满转速）：13w

以上*功率共计512w*（整数），官方推荐的450w还真不够看，650w算是够用了。

=== How?

鉴于之前的几次装机的经验，我对装机基本法还是有些了解的。但鉴于这是我第一次使用老平台搭建服务器，肯定会发现不少问题，诸如内存不兼容、BIOS升级、性能调教等等。但好在x99现仍是垃圾佬的标配，网上有大量的装机经验可以参考借鉴，这也肯定能成为我本次烧钱之旅的助力。

=== Finally...

同时这也是我要写这个系列的原因之一，希望这个系列能够总结出一些东西，避免各位之后踩坑。能让各位在看个乐子的同时能有所得，我的目的就已经达成了。